/* ═══════════════════════════════════════════════════════════════════════════
   Bee's GSU Grad Planner — degree data (B.S. Computer Science)
   Requirements: Degree Works structure for catalog year 2024–2025 and the GSU
   2024–2025 Undergraduate Catalog, "Computer Science, B.S.".
   Prerequisites: GSU 2026–2027 catalog (current), checked against PAWS for Fall 2026.
   Offering history: GSU class schedules, Spring 2024 – Fall 2026 (non-lab section counts).
   No grades or course history here: the academic record is loaded from Firebase.
   ═══════════════════════════════════════════════════════════════════════════ */

/* ─── Planner settings ───────────────────────────────────────────────────── */
const PLAN_START = { season:'spring', year:2027 };   // first term open for planning
const DEFAULT_SEMESTER_COUNT = 3;                     // Spring 2027 → Fall 2027
const MAX_SEMESTER_COUNT = 12;
const MAX_CREDITS_PER_TERM = 18;                      // GSU catalog 1330.30: up to 18 hours (summer too) without special permission
const PLAN_VERSION = 6;                               // bump when saved plans need migrating
const RECORD_VERSION = 1;

const DAY_ORDER  = ['M','T','W','Th','F'];
const DAY_LABELS = { M:'Mon', T:'Tue', W:'Wed', Th:'Thu', F:'Fri' };
const BLOCK_TYPES = ['Lecture','Lab','Recitation','Discussion','Other'];

// Terms covered by each course's `offered` array (number of sections per term).
const OFFERING_TERMS = [{ season:'spring', year:2024 }, { season:'summer', year:2024 }, { season:'fall', year:2024 }, { season:'spring', year:2025 }, { season:'summer', year:2025 }, { season:'fall', year:2025 }, { season:'spring', year:2026 }, { season:'summer', year:2026 }, { season:'fall', year:2026 }];

/* ─── Degree structure (Degree Works blocks and requirement lines) ────────── */
const DEGREE = {"program": "B.S. in Computer Science", "catalogYear": "2024–2025", "totalCredits": 120, "offeringsWindow": "Spring 2024 – Fall 2026"};

const BLOCKS = [
  {"key": "core", "name": "IMPACTS Core", "short": "Core", "dw": "CAS IMPACTS Core Curriculum", "credits": 42, "note": "IMPACTS core areas for the 2024–2025 catalog."},
  {"key": "advice", "name": "Program Advice", "short": "Advice", "dw": "ASBS_Computer Science - Program Advice", "credits": null, "shared": true, "note": "Computer Science majors must complete MATH 2211 with a C or better. It also counts in the IMPACTS Core."},
  {"key": "fos", "name": "Field of Study", "short": "Field of Study", "dw": "Field of Study - Computer Science", "credits": 18, "note": "A minimum grade of C is required in all mathematics and computer science courses."},
  {"key": "major", "name": "Major", "short": "Major", "dw": "Major - Computer Science", "credits": 48, "note": "Internship CSC 4940 cannot apply toward the major. Up to 4 credit hours from CSC 4870, 4880, 4980 and 4982 may count."},
  {"key": "rpe", "name": "Required Program Electives – CSC", "short": "Program Electives", "dw": "Required Program Electives - CSC", "credits": 12, "note": "Additional 12 hours at the 2000–4000 level in any subject, not only CSC. Average GPA of C or better in this area."},
];

// credits/count: what the line needs · courses: codes that fill it · pattern: subject/level rule · list: pick-from-a-list line
const REQUIREMENT_LINES = [
  {"id": "core.inst", "block": "core", "group": "Institutional Priority (4 credits)", "label": "Institutional Priority", "credits": 4, "count": null, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": "Only one PERS 2001, 2002 or 2003 may count here."},
  {"id": "core.math", "block": "core", "group": "Mathematics & Quantitative Skills (3–4 credits)", "label": "Mathematics & Quantitative Skills", "credits": 3, "count": null, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": ""},
  {"id": "core.amgov", "block": "core", "group": "Political Science and U.S. History (6 credits)", "label": "American Government", "credits": 3, "count": null, "courses": ["POLS 1101"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "", "note": ""},
  {"id": "core.ushist", "block": "core", "group": "Political Science and U.S. History (6 credits)", "label": "U.S. History", "credits": 3, "count": null, "courses": ["HIST 2110"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "", "note": ""},
  {"id": "core.hum", "block": "core", "group": "Arts, Humanities & Ethics (6 credits)", "label": "Humanities", "credits": null, "count": 1, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": ""},
  {"id": "core.lang", "block": "core", "group": "Arts, Humanities & Ethics (6 credits)", "label": "World Language", "credits": null, "count": 1, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": ""},
  {"id": "core.engl1", "block": "core", "group": "Communicating in Writing (6 credits)", "label": "English Composition I", "credits": 3, "count": null, "courses": ["ENGL 1101"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "core.engl2", "block": "core", "group": "Communicating in Writing (6 credits)", "label": "English Composition II or Advanced English Comp", "credits": 3, "count": null, "courses": ["ENGL 1102"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "core.labseq", "block": "core", "group": "Technology, Mathematics & Sciences (11 credits)", "label": "Lab Science Sequence: Principles of Physics", "credits": 8, "count": null, "courses": ["PHYS 2211K", "PHYS 2211", "PHYS 2211L", "PHYS 2212K", "PHYS 2212", "PHYS 2212L"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "", "note": "Both courses of one lab-science sequence. PHYS 2212K is now PHYS 2212 (3 cr) + PHYS 2212L (1 cr)."},
  {"id": "core.stem", "block": "core", "group": "Technology, Mathematics & Sciences (11 credits)", "label": "STEM Course (see Program Advice)", "credits": null, "count": 1, "courses": ["MATH 2211"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "", "note": ""},
  {"id": "core.global", "block": "core", "group": "Social Sciences (6 credits)", "label": "Global Economics, Politics & World History", "credits": null, "count": 1, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": ""},
  {"id": "core.socfound", "block": "core", "group": "Social Sciences (6 credits)", "label": "Social Science Foundations", "credits": null, "count": 1, "courses": [], "pattern": null, "list": false, "recordOnly": true, "minGrade": "", "note": ""},
  {"id": "advice.calc", "block": "advice", "group": "", "label": "STEM Major Calculus Requirement", "credits": 4, "count": null, "courses": ["MATH 2211"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "fos.csc1301", "block": "fos", "group": "", "label": "4 Credits CSC 1301", "credits": 4, "count": null, "courses": ["CSC 1301"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "fos.csc1302", "block": "fos", "group": "", "label": "4 Credits CSC 1302", "credits": 4, "count": null, "courses": ["CSC 1302"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "fos.calc2", "block": "fos", "group": "", "label": "Calculus of One Variable II", "credits": 4, "count": null, "courses": ["MATH 2212"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "fos.theory", "block": "fos", "group": "", "label": "Theoretical Foundations of Computer Science", "credits": 3, "count": null, "courses": ["MATH 2420", "CSC 2510"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "fos.addl", "block": "fos", "group": "", "label": "Select Additional Credits to reach 18 hrs from the Following", "credits": 3, "count": null, "courses": ["ACCT 2101", "ACCT 2102", "ASTR 1010K", "ASTR 1020K", "BIOL 1103K", "BIOL 1104K", "BIOL 2107K", "BIOL 2108K", "BIOL 2107", "BIOL 2107L", "BIOL 2108", "BIOL 2108L", "CHEM 1211K", "CHEM 1212K", "CHEM 2400", "CSC 2920", "ECON 2105", "ECON 2106", "GEOL 1121K", "GEOL 1122K", "MATH 2215", "SCOM 1500", "SCOM 2300", "DSCI 1301", "DSCI 1302", "PHYS 2212K", "ASTR 1010", "ASTR 1010L", "ASTR 1020", "ASTR 1020L", "BIOL 1103", "BIOL 1103L", "BIOL 1104", "BIOL 1104L", "CHEM 1211", "CHEM 1211L", "CHEM 1212", "CHEM 1212L", "GEOL 1121", "GEOL 1121L", "GEOL 1122", "GEOL 1122L", "PHYS 2212", "PHYS 2212L"], "pattern": null, "list": true, "recordOnly": false, "minGrade": "", "note": "One course from the list completes the line; the Field of Study also needs 18 credits in total."},
  {"id": "major.linalg", "block": "major", "group": "", "label": "Linear Algebra", "credits": 3, "count": null, "courses": ["MATH 2641"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.prob", "block": "major", "group": "", "label": "Applied Probability & Statistics", "credits": 3, "count": null, "courses": ["MATH 3020"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.ds", "block": "major", "group": "", "label": "Data Structures", "credits": 3, "count": null, "courses": ["CSC 2720"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.ctw", "block": "major", "group": "", "label": "CTW: Software Development", "credits": 4, "count": null, "courses": ["CSC 3350"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.comporg", "block": "major", "group": "", "label": "Computer Org & Programming", "credits": 4, "count": null, "courses": ["CSC 3210", "CSC 3210L"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": "CSC 3210 (3 cr) plus the CSC 3210L lab (1 cr)."},
  {"id": "major.syslevel", "block": "major", "group": "", "label": "System Level Programming", "credits": 3, "count": null, "courses": ["CSC 3320"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.osplc", "block": "major", "group": "", "label": "Operating Systems or Programming Language Concepts", "credits": 4, "count": null, "courses": ["CSC 4320", "CSC 4330"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.algo", "block": "major", "group": "", "label": "Design & Analysis: Algorithms", "credits": 4, "count": null, "courses": ["CSC 4520"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.cap1", "block": "major", "group": "", "label": "Capstone Senior Design I", "credits": 2, "count": null, "courses": ["CSC 4351"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.cap2", "block": "major", "group": "", "label": "Capstone Senior Design II", "credits": 2, "count": null, "courses": ["CSC 4352"], "pattern": null, "list": false, "recordOnly": false, "minGrade": "C", "note": ""},
  {"id": "major.elec", "block": "major", "group": "", "label": "3000/4000 level CSC Electives", "credits": 16, "count": null, "courses": [], "pattern": {"subject": "CSC", "min": 3000, "max": 4999, "exclude": ["CSC 3900", "CSC 4940", "CSC 4990", "CSC 4995", "CSC 4998", "CSC 4999"], "limited": ["CSC 4870", "CSC 4880", "CSC 4900", "CSC 4980", "CSC 4982"], "limitedMax": 4}, "list": false, "recordOnly": false, "minGrade": "C", "note": "16 credits in CSC 3000/4000 courses except CSC 3900, 4940, 4990, 4995, 4998 and 4999."},
  {"id": "rpe.hours", "block": "rpe", "group": "", "label": "2000:4999 Additional Hours", "credits": 12, "count": null, "courses": [], "pattern": {"subject": "", "min": 2000, "max": 4999, "exclude": [], "limited": [], "limitedMax": 0}, "list": false, "recordOnly": false, "minGrade": "", "note": "Any subject at the 2000–4000 level."},
];

// A course that fills a line only after the advisor records a Degree Works exception.
const SUBSTITUTIONS = [{"course": "CSC 4350", "line": "major.cap1", "complete": ["major.cap2"], "label": "CSC 4350 Software Engineering in place of Capstone Senior Design I and II", "applyNote": "Apply Here: Substitute for Capstone courses to graduate.", "completeNote": "Force Complete: Course not needed because of substitution."}];

/* ─── Grades (GSU catalog 1350) ──────────────────────────────────────────── */
const GRADE_POINTS = {"A+": 4.3, "A": 4.0, "A-": 3.7, "B+": 3.3, "B": 3.0, "B-": 2.7, "C+": 2.3, "C": 2.0, "C-": 1.7, "D": 1.0, "F": 0.0, "WF": 0.0};
const GRADE_OPTIONS = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F", "WF", "W", "WM", "I", "IP", "S", "U", "V", "K", "NR"];
const MIN_GRADE_RULES = {"subjects": {"CSC": "C", "MATH": "C"}, "codes": {"ENGL 1101": "C", "ENGL 1102": "C"}, "fallback": "D"};

/* ─── GPA rules ──────────────────────────────────────────────────────────────
   Catalog 1350.20 and 1350.25 (same text in 2024–25 and 2026–27), catalog 1330.35
   and 1360, and the Registrar's Grading and Repeat-to-Replace pages. planner.js applies them.
   ────────────────────────────────────────────────────────────────────────── */
const GPA_RULES = {
  maxGradePoints: 4.3,        // A+ = 4.30
  r2rMaxCourses: 4,           // "no more than a total of four course grades (from four different courses)"
  r2rFirstTerm: 'fall2011',   // the repeat must be taken Fall 2011 or later
};
const GPA_SOURCES = [
  { label: 'Catalog 1350 The Grading System (2026–27)', url: 'https://catalogs.gsu.edu/content.php?catoid=46&navoid=5905' },
  { label: 'Catalog 1350 (2024–25 — same text)', url: 'https://catalogs.gsu.edu/content.php?catoid=38&navoid=4999' },
  { label: 'Registrar: Repeat-to-Replace', url: 'https://registrar.gsu.edu/academic-records/grading/repeat-to-replace/' },
  { label: 'Registrar: Grading', url: 'https://registrar.gsu.edu/academic-records/grading/' },
  { label: 'Catalog 1330.35 Taking a Course More Than Once', url: 'https://catalogs.gsu.edu/content.php?catoid=46&navoid=5893' },
  { label: 'Catalog 1360 Academic Support (standing)', url: 'https://catalogs.gsu.edu/content.php?catoid=46&navoid=5909' },
];
const GPA_RULE_SUMMARY = [
  'Grade points: A+ 4.30 · A 4.00 · A− 3.70 · B+ 3.30 · B 3.00 · B− 2.70 · C+ 2.30 · C 2.00 · C− 1.70 · D 1.00 · F 0 · WF 0 (counts like F).',
  'Never in a GPA: W, WM, I, IP, S, U, V, K (credit by exam) and NR, plus Learning Support (remedial) courses, CLEP, AP and IB credit.',
  'GSU GPA = GSU quality points ÷ GSU hours attempted. GSU + transfer GPA adds transfer grades, weighted by the converted semester hours (3.33 for a 5-quarter-hour course).',
  'Every attempt counts, including repeats — unless Repeat to Replace removes the first grade. The last attempt decides whether a course meets a degree requirement.',
  'Repeat to Replace: retake the course at GSU and earn a higher grade; only the first recorded grade can be replaced; at most 4 courses; W, S and U can’t be replaced; an approval can’t be undone; every attempt stays on the transcript; the HOPE GPA doesn’t change.',
  'GPAs are rounded to the hundredth (for example 3.456 → 3.46). Academic standing uses the GSU GPA and term GPA.',
];
// How to request Repeat to Replace (Registrar).
const R2R_HOW_TO = 'Apply after the retake’s final grade is posted: submit the Registrar’s online Repeat-to-Replace Application (original course, term, grade, CRN and instructor, plus the retake’s). In the graduation semester, apply within the first two weeks — it is honored only if the higher grade is needed to graduate.';
// What the official sources leave open.
const GPA_OPEN_QUESTIONS = [
  'Repeat to Replace is written for the institutional (GSU) GPA. The GSU + transfer GPA is the GSU GPA plus transfer grades, so the app removes the replaced grade from both — confirm with the Registrar.',
  'The catalog’s grade table lists IP as 0.00, but the same section says IP is never used in a GPA. The app leaves IP out.',
  'The catalog rounds GPAs to the hundredth but doesn’t show an exact .xx5 case; the app rounds it up. The Advisement GPA calculator truncates instead, and it is only an estimate.',
  'A+ (4.30) counts at GSU, but not every instructor gives it — the “all A” numbers are the safer plan.',
  'Transfer grades are converted by GSU. Converted points can differ slightly from the letter shown, so GSU + transfer estimates can be off by about 0.01.',
  'Degree Works adds “$” to transfer grades (and “%” to Learning Support grades), but no public GSU source defines these marks. The app counts a “$” grade as its letter on transfer credit, which reproduces her official GSU + transfer GPA.',
  'Repeat to Replace doesn’t change the HOPE GPA or other state or federal GPA requirements (such as financial-aid progress).',
  'Academic standing uses the GSU GPA, so an approved Repeat to Replace raises the GPA used for standing from then on. The policy doesn’t say whether earlier standing is recalculated.',
  'Repeat to Replace also requires that the first grade wasn’t given for an academic honesty violation, that this is her first undergraduate degree at GSU, and that her college doesn’t bar repeating the course.',
];

/* ─── Course library ──────────────────────────────────────────────────────────
   section: library section · tag: sub-group · prereq: AND-list of course ids or [any-of] lists
   parts: lecture + lab registered separately · aliases: older course numbers
   ────────────────────────────────────────────────────────────────────────── */
const FOS_NOTE = "Pick from this list. One course completes the line; the Field of Study also needs 18 credits in total, which a 4-credit course reaches on its own.";
const RPE_NOTE = "Any 2000–4000 level course in any subject counts in Required Program Electives – CSC; these are examples.";
const COURSES = [
  {"id": "MATH2641", "code": "MATH 2641", "title": "Linear Algebra I", "credits": 3, "level": 2641, "section": "major", "tag": "req", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["MATH2211", "MATH2201"]], "prereqText": "MATH 2201 or MATH 2211 with a C or higher.", "note": "", "offered": [11, 11, 9, 10, 8, 8, 10, 9, 8], "description": "Theory and applications of matrix algebra, vector spaces, and linear transformations. Topics include linear equations and matrices, invertible matrices, determinants, vector spaces, subspaces, bases, eigenvalues and eigenvectors."},
  {"id": "MATH3020", "code": "MATH 3020", "title": "Applied Probability & Statistics for CS", "credits": 3, "level": 3020, "section": "major", "tag": "req", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["MATH2212"], "prereqText": "MATH 2212 with a C or higher.", "note": "Required before CSC 4520 (Algorithms), CSC 4220 and CSC 4223.", "offered": [5, 3, 5, 5, 2, 5, 5, 2, 4], "description": "This course covers theory and applications of probability models, random variables, discrete and continuous probability distributions, joint and conditional distributions, sampling distributions, central limit theorem, hypothesis testing, confidence intervals, and exposure to simple linear regression. Time-to-failure probability models are considered."},
  {"id": "CSC3350", "code": "CSC 3350", "title": "Software Development (CTW)", "credits": 4, "level": 3350, "section": "major", "tag": "req", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "Critical Thinking Through Writing course. Required before Capstone I (CSC 4351).", "offered": [3, 1, 2, 3, 1, 2, 3, 1, 2], "description": "This course is intended to teach the disciplined process of software design. Using system development methods, from formal specification of Unified Modeling Language (UML) for supporting software development, through engineering practices such as design, testing, and developing system architecture via design patterns. Critical Thinking through Writing course. Critical Thinking through Writing course."},
  {"id": "CSC3210", "code": "CSC 3210 + 3210L", "title": "Computer Organization & Programming + Lab", "credits": 4, "level": 3210, "section": "major", "tag": "req", "kind": "Lecture (3 cr) + Lab CSC 3210L (1 cr)", "parts": [{"code": "CSC 3210", "credits": 3}, {"code": "CSC 3210L", "credits": 1}], "aliases": [], "prereq": ["CSC1302", ["CSC2510", "MATH2420"]], "prereqText": "CSC 1302, and CSC 2510 or MATH 2420, with a C or higher. CSC 3210 (3 cr) and CSC 3210L (1 cr) are corequisites.", "note": "A 3-credit lecture plus the 1-credit CSC 3210L lab. Register for both in the same term; together they satisfy the 4-credit Computer Org & Programming line.", "offered": [12, 3, 15, 12, 3, 12, 12, 2, 3], "description": "This course introduces the principles of computer architecture and assembly and machine language. Topics include principles of computer architecture, binary and hexadecimal arithmetic, signed and unsigned arithmetic, memory organization, addressing modes, procedure calls, the stack frame, floating point unit and instruction encoding, as well as writing assembly language programs. The course also covers the basics of CISC vs. RISC architecture and parallel architecture models and programming. The CSC 3210L lab applies these topics in weekly lab sessions."},
  {"id": "CSC3320", "code": "CSC 3320", "title": "System-Level Programming", "credits": 3, "level": 3320, "section": "major", "tag": "req", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC1302", "DSCI1302"], ["CSC2510", "MATH2420"]], "prereqText": "(CSC 1302 or DSCI 1302) and (CSC 2510 or MATH 2420) with a C or higher.", "note": "Unlocks CSC 4320 and most CSC electives — take it early.", "offered": [13, 3, 15, 12, 3, 12, 12, 3, 6], "description": "An introduction to programming at the level of the operating system. Topics include editors, system calls, programming tools, files, processes, interprocess communication, and shells."},
  {"id": "CSC4520", "code": "CSC 4520", "title": "Design & Analysis of Algorithms", "credits": 4, "level": 4520, "section": "major", "tag": "req", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"], ["MATH3020", "MATH3030"]], "prereqText": "(CSC 2720 or DSCI 2720) and (MATH 3020 or MATH 3030) with a C or higher.", "note": "", "offered": [6, 2, 5, 7, 1, 5, 6, 1, 4], "description": "Techniques for designing efficient algorithms; analysis of algorithms; lower bound arguments; algorithms for sorting, selection, graphs, and string matching."},
  {"id": "CSC4320", "code": "CSC 4320", "title": "Operating Systems", "credits": 4, "level": 4320, "section": "major", "tag": "osplc", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "Pick CSC 4320 or CSC 4330 for the requirement; taking both counts the second as a CSC elective.", "offered": [4, 1, 4, 3, 1, 4, 3, 1, 4], "description": "Introduction to operating systems concepts. Topics may include multiprogramming, resources allocation and management, and their implementation."},
  {"id": "CSC4330", "code": "CSC 4330", "title": "Programming Language Concepts", "credits": 4, "level": 4330, "section": "major", "tag": "osplc", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3210", "CSC3320"], "prereqText": "CSC 2720, CSC 3210 and CSC 3320 with a C or higher.", "note": "Pick CSC 4320 or CSC 4330 for the requirement; taking both counts the second as a CSC elective.", "offered": [5, 1, 5, 5, 1, 5, 4, 0, 3], "description": "Fundamental programming language concepts, including syntax versus semantics, binding time, scopes, and storage management."},
  {"id": "CSC4350", "code": "CSC 4350", "title": "Software Engineering (CTW)", "credits": 4, "level": 4350, "section": "major", "tag": "capstone", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3210", "CSC3320"], "prereqText": "CSC 2720, CSC 3210 and CSC 3320 with a C or higher.", "note": "The one-term capstone. Degree Works lists Capstone Senior Design I and II (CSC 4351 + 4352), so the advisor enters an exception — “Apply Here: Substitute for Capstone courses” on Senior Design I and “Force Complete: Course not needed because of substitution” on Senior Design II — ideally before you register. Offered every Fall, Spring and Summer (2024–2026); summer sections have been online and fill quickly.", "offered": [5, 2, 3, 3, 1, 3, 3, 1, 3], "description": "This course focuses on techniques used in large scale scientific or technical software development, including requirements analysis, specification, systems design, implementation, testing, validation, verification, and maintenance. Serves as the Critical Thinking Through Writing (CTW) course, as well as the capstone experience, required of all Computer Science majors. Serves as the Critical Thinking Through Writing (CTW) course, as well as the capstone experience, required of all Computer Science majors."},
  {"id": "CSC4351", "code": "CSC 4351", "title": "Capstone Senior Design I (CTW)", "credits": 2, "level": 4351, "section": "major", "tag": "capstone", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3350"], "prereqText": "CSC 3350 with a C or higher.", "note": "First half of the two-term capstone. Offered only in Fall (2024–2026); CSC 4352 follows in Spring. CSC 4350 covers both in one term with an advisor exception.", "offered": [0, 0, 2, 0, 0, 2, 0, 0, 2], "description": "This first course in a sequence of two consecutive courses integrates software engineering knowledge, formal software design principles, and tools/technologies for software system creation. Students form a team and choose a project topic through the guidance of a governing faculty. The faculty or professional leadership forms the “client” for a software development team that results from reporting a solution to some problem in software engineering. Serves as a Critical Thinking Through Writing course."},
  {"id": "CSC4352", "code": "CSC 4352", "title": "Capstone Senior Design II (CTW)", "credits": 2, "level": 4352, "section": "major", "tag": "capstone", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC4351"], "prereqText": "CSC 4351 with a C or higher.", "note": "Second half of the capstone. Offered only in Spring (2025–2026).", "offered": [0, 0, 0, 1, 0, 0, 1, 0, 0], "description": "This course helps student teams gain new experience in software implementation. The student teams are guided by a governing faculty, including research faculty, or academic professionals and may include industry alignment. Student teams will use software system implementation techniques through team collaboration, Agile sprint cycles with system functional demonstrations, and project progression analysis and reporting. Serves as a Critical Thinking Through Writing course."},
  {"id": "PHYS2212", "code": "PHYS 2212 + 2212L", "title": "Principles of Physics II + Lab", "credits": 4, "level": 2212, "section": "core", "tag": "labseq", "kind": "Lecture (3 cr) + Lab PHYS 2212L (1 cr)", "parts": [{"code": "PHYS 2212", "credits": 3}, {"code": "PHYS 2212L", "credits": 1}], "aliases": ["PHYS 2212K"], "prereq": [["MATH2212", "MATH2202"], ["PHYS2211K", "PHYS2211"]], "prereqText": "MATH 2212 (or 2202) and PHYS 2211K (or PHYS 2211 + 2211L), all with a C or higher. PHYS 2212 and PHYS 2212L are corequisites.", "note": "Second course of the Principles of Physics lab sequence. A 3-credit lecture plus the 1-credit PHYS 2212L lab — take both; together they are the 4-credit PHYS 2212K. Summer 2024–2026 sections ran only at Perimeter campuses, which Atlanta students may take only with advance written authorization, so plan it for Fall or Spring.", "offered": [14, 5, 12, 15, 5, 12, 13, 5, 7], "description": "This is the second in a calculus based two course survey of the primary fields of physics. This course will cover electromagnetism, optics, and modern physics. The PHYS 2212L lab reinforces the lecture concepts."},
  {"id": "ECON2105", "code": "ECON 2105", "title": "Principles of Macroeconomics", "credits": 3, "level": 2105, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "Catalog lists MATH 1001 or MATH 1111; PAWS does not enforce a prerequisite.", "note": "It is 2000-level, so a second list course like this counts in Required Program Electives – CSC.", "offered": [39, 20, 42, 43, 23, 39, 44, 15, 35], "description": "This course analyzes the overall performance of economic systems including output and employment levels, inflation, economic growth, international finance, and the effects of monetary and fiscal policies."},
  {"id": "ECON2106", "code": "ECON 2106", "title": "Principles of Microeconomics", "credits": 3, "level": 2106, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "Catalog lists MATH 1001 or MATH 1111; PAWS does not enforce a prerequisite.", "note": "It is 2000-level, so a second list course like this counts in Required Program Electives – CSC. Take it after your Field of Study course so Degree Works applies it there.", "offered": [36, 12, 37, 37, 18, 36, 32, 18, 33], "description": "This course is a systematic study of the functions of markets and prices in the production and distribution of goods and includes economic analysis of international trade, public finance, labor markets, monopoly, and poverty."},
  {"id": "ACCT2101", "code": "ACCT 2101", "title": "Principles of Accounting I", "credits": 3, "level": 2101, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "None.", "note": "It is 2000-level, so a second list course like this counts in Required Program Electives – CSC.", "offered": [30, 15, 39, 40, 21, 44, 40, 19, 44], "description": "Principles of Accounting I is an introduction to the principles of financial accounting. The course focuses on analyzing business transactions to chart their effects on the results of operations, the cash flows, and the financial position of businesses organized for profit. Emphasis is on using financial information from a decision-making perspective to optimize the outcomes of business decisions. Topics include recording, reporting, and analyzing assets, liabilities, stockholders’ equity, revenues, and expenses."},
  {"id": "ACCT2102", "code": "ACCT 2102", "title": "Principles of Accounting II", "credits": 3, "level": 2102, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["ACCT2101"], "prereqText": "ACCT 2101.", "note": "It is 2000-level, so a second list course like this counts in Required Program Electives – CSC.", "offered": [22, 12, 20, 24, 14, 24, 25, 12, 24], "description": "Principles of Accounting II is an introduction to the principles of managerial accounting. Emphasis is given to the development and use of accounting information to support managerial decision-making in manufacturing, service, and merchandising operations. Topics include managerial concepts and systems, analyses for decision making, and planning and control."},
  {"id": "SCOM1500", "code": "SCOM 1500", "title": "Public Speaking", "credits": 3, "level": 1500, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "None.", "note": "1000-level, so it counts only in the Field of Study.", "offered": [20, 10, 22, 19, 11, 22, 19, 11, 20], "description": "Preparation and delivery of speeches to inform and to persuade. Special emphasis is placed on the fundamentals of organization, structure, and content of speeches. The student will analyze great American speeches, both historical and contemporary."},
  {"id": "CSC2920", "code": "CSC 2920", "title": "Ethical & Social Issues in Computing", "credits": 3, "level": 2920, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC1301", "CSC1302"], "prereqText": "CSC 1301 and CSC 1302 with a C or higher.", "note": "Offered Fall and Spring (not Summer) in 2024–2026.", "offered": [1, 0, 1, 1, 0, 3, 3, 0, 3], "description": "This course is dedicated to the study of social, ethical, and legal effects of computing on society and its users. Ethical concepts, professional codes of ethics, and the influence of computing on individuals, organizations, and the global economy will be addressed. Students will utilize critical thinking and problem solving skills to analyze and debate case studies on topics some of which include privacy; intellectual property; computer crimes; system failures and implications; and, the impact of technology on society."},
  {"id": "MATH2215", "code": "MATH 2215", "title": "Multivariate Calculus", "credits": 4, "level": 2215, "section": "fos", "tag": "fos", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["MATH2212"], "prereqText": "MATH 2212 with a C or higher.", "note": "The only single 4-credit course on the list: it completes the line and the 18-hour Field of Study total at once.", "offered": [6, 4, 4, 5, 3, 4, 5, 3, 4], "description": "Real-valued functions of several variables, limits, continuity, differentials, directional derivatives, partial derivatives, chain rule, multiple integrals, applications."},
  {"id": "ASTR1010", "code": "ASTR 1010 + 1010L", "title": "Astronomy of the Solar System + Lab", "credits": 4, "level": 1010, "section": "fos", "tag": "fos", "kind": "Lecture (3 cr) + Lab (1 cr)", "parts": [{"code": "ASTR 1010", "credits": 3}, {"code": "ASTR 1010L", "credits": 1}], "aliases": ["ASTR 1010K"], "prereq": [], "prereqText": "No prerequisite. ASTR 1010 and ASTR 1010L are corequisites.", "note": "Lecture + lab, 4 credits together. Degree Works lists ASTR 1010K — ask your advisor to confirm both parts apply to the Field of Study.", "offered": [27, 7, 35, 28, 8, 34, 26, 8, 17], "description": "Co-requisites: Astr 1010L. Astronomy from early ideas of the cosmos to modern observational techniques. The solar system planets, satellites, and minor bodies. The origin and evolution of the solar system."},
  {"id": "GEOL1121", "code": "GEOL 1121 + 1121L", "title": "Introductory Geology I + Lab", "credits": 4, "level": 1121, "section": "fos", "tag": "fos", "kind": "Lecture (3 cr) + Lab (1 cr)", "parts": [{"code": "GEOL 1121", "credits": 3}, {"code": "GEOL 1121L", "credits": 1}], "aliases": ["GEOL 1121K"], "prereq": [], "prereqText": "No prerequisite. GEOL 1121 and GEOL 1121L are corequisites.", "note": "Lecture + lab, 4 credits together. Degree Works lists GEOL 1121K — ask your advisor to confirm both parts apply to the Field of Study.", "offered": [22, 7, 29, 22, 8, 28, 21, 8, 27], "description": "Co-requisite: GEOL 1121L. This course covers the formation and internal structure of the Earth, plate tectonics, earthquakes,volcanism, minerals, and rocks."},
  {"id": "BIOL1103", "code": "BIOL 1103 + 1103L", "title": "Introductory Biology I + Lab", "credits": 4, "level": 1103, "section": "fos", "tag": "fos", "kind": "Lecture (3 cr) + Lab (1 cr)", "parts": [{"code": "BIOL 1103", "credits": 3}, {"code": "BIOL 1103L", "credits": 1}], "aliases": ["BIOL 1103K"], "prereq": [], "prereqText": "No prerequisite. BIOL 1103 and BIOL 1103L are corequisites.", "note": "Lecture + lab, 4 credits together. Degree Works lists BIOL 1103K — ask your advisor to confirm both parts apply to the Field of Study.", "offered": [52, 13, 40, 37, 10, 42, 38, 11, 42], "description": "Co-requisite: BIOL 1103L. Introduction to fundamental concepts in biology, with an emphasis on evolution, cell structure and function, basic chemistry of life, gene structure and function, cell division, and genetics. Application of these concepts to issues affecting society. This course does not fulfill the requirements for a major in biology. This course does not fulfill the requirements for a major in biology."},
  {"id": "BIOL2107", "code": "BIOL 2107 + 2107L", "title": "Principles of Biology I + Lab", "credits": 4, "level": 2107, "section": "fos", "tag": "fos", "kind": "Lecture (3 cr) + Lab (1 cr)", "parts": [{"code": "BIOL 2107", "credits": 3}, {"code": "BIOL 2107L", "credits": 1}], "aliases": ["BIOL 2107K"], "prereq": [], "prereqText": "MATH 1111 (or placement into MATH 1113 or higher). BIOL 2107 and BIOL 2107L are corequisites.", "note": "Lecture + lab, 4 credits together; science-majors biology. Degree Works lists BIOL 2107 and 2107L by name.", "offered": [8, 2, 8, 8, 2, 10, 8, 2, 12], "description": "Introduction to scientific method, theory and experimentation, cell chemistry, enzymes, metabolism, photosynthesis, genetics, and evolution, and a survey of selected organisms. Fulfills Biology major requirement."},
  {"id": "CHEM1211", "code": "CHEM 1211 + 1211L", "title": "Principles of Chemistry I + Lab", "credits": 4, "level": 1211, "section": "fos", "tag": "fos", "kind": "Lecture (3 cr) + Lab (1 cr)", "parts": [{"code": "CHEM 1211", "credits": 3}, {"code": "CHEM 1211L", "credits": 1}], "aliases": ["CHEM 1211K"], "prereq": [], "prereqText": "MATH 1111 or higher with a C or higher. CHEM 1211 and CHEM 1211L are corequisites.", "note": "Lecture + lab, 4 credits together. Degree Works lists CHEM 1211K — ask your advisor to confirm both parts apply to the Field of Study. Science-majors chemistry.", "offered": [36, 12, 57, 15, 7, 21, 16, 7, 22], "description": "This is the first course in a two-semester sequence covering the fundamental principles and applications of chemistry for science majors. Topics include composition of matter, chemical reactions, stoichiometry, periodic relations, nomenclature, thermochemistry, electronic structure, chemical bonding, molecular geometry, and properties of gases. Three lecture hours a week. Three lecture hours a week."},
  {"id": "PERS2001", "code": "PERS 2001", "title": "Perspectives on Comparative Culture", "credits": 2, "level": 2001, "section": "rpe", "tag": "rpe", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "None.", "note": "2 credits at the 2000 level. The only 2-credit course open to CS majors every summer in 2024–2026: online sections in the 7-week session, and some in the 3-week May session. Ask your advisor to confirm it counts in Required Program Electives – CSC.", "offered": [12, 9, 13, 14, 7, 12, 10, 6, 12], "description": "A group of interdisciplinary courses that provides a better understanding of the contemporary world through the study of different cultures."},
  {"id": "JAPN2001", "code": "JAPN 2001", "title": "Intermediate Japanese I", "credits": 3, "level": 2001, "section": "rpe", "tag": "rpe", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["JAPN1002"], "prereqText": "JAPN 1002 with a C or higher, or placement into 2001.", "note": "Offered Fall and Spring (not Summer) in 2024–2026.", "offered": [2, 0, 1, 2, 0, 1, 1, 0, 1], "description": "Intermediate grammar; practice in conversation, composition, and reading. Japanese culture presented."},
  {"id": "PHIL2920", "code": "PHIL 2920", "title": "Ethics of Computing", "credits": 3, "level": 2920, "section": "rpe", "tag": "rpe", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "None listed.", "note": "Newer catalogs list it with the Field of Study; under the 2024–25 catalog it counts here. First offered Fall 2025.", "offered": [0, 0, 0, 0, 0, 2, 2, 0, 2], "description": "Discussion of ethical and social issues raised by advancements in computing, artificial intelligence, or other information technologies. Students will utilize ethical reasoning, critical thinking, and problem-solving skills to analyze and debate case studies on topics such as autonomous weapons, self-driving cars, cybersecurity, system failures, privacy and speech in the information age, intellectual property, professional ethics, and the impact of big data on fairness and transparency."},
  {"id": "CSC3780", "code": "CSC 3780", "title": "Fundamentals of Data Science", "credits": 4, "level": 3780, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or better.", "note": "Renumbered from CSC 4780 in Fall 2026 — take only one of them.", "offered": [2, 0, 2, 2, 0, 3, 3, 0, 2], "description": "Introduction to the fundamental concepts of predictive data science for tabular data with qualitative and quantitative scales. Topics include: data exploration, pre-processing and visualization; analytics base table (ABT) generation; basic supervised learning algorithms (i.e. information-based learning, similarity-based learning, and error-based learning), and comparative evaluation of these algorithms."},
  {"id": "CSC4120", "code": "CSC 4120", "title": "Introduction to Robotics", "credits": 4, "level": 4120, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3210"], "prereqText": "CSC 3210 with a C or higher.", "note": "", "offered": [1, 0, 1, 0, 0, 1, 0, 0, 1], "description": "The course focuses on programming robots. We will use robotic kits for the hardware, and program them using state-of-the-art languages, such as NQC."},
  {"id": "CSC4210", "code": "CSC 4210", "title": "Computer Architecture", "credits": 4, "level": 4210, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3210"], "prereqText": "CSC 3210 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "Logic design, combinatorial and sequential circuits, input-output devices, memory, processors, controllers, parallel architectures, bit-slicing, reduced instruction sets."},
  {"id": "CSC4220", "code": "CSC 4220", "title": "Computer Networks", "credits": 4, "level": 4220, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320", ["MATH3020", "MATH3030"]], "prereqText": "CSC 3320 and either MATH 3020 or MATH 3030 with a C or higher.", "note": "", "offered": [1, 0, 1, 1, 0, 1, 1, 0, 1], "description": "Introduction to computer networks; details of layered network protocols with emphasis on functionality and analysis. Principles of relevant state-of-the-art network standards."},
  {"id": "CSC4221", "code": "CSC 4221", "title": "Mobile Computing & Wireless Network Security", "credits": 4, "level": 4221, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 1, 0, 0, 1, 0, 0, 1], "description": "Introduction to wireless communication networks and mobile computing. Topics include: wireless communications technology; communication protocols in wireless networks; representative network types such as cellular wireless networks, wireless LANs, wireless ad hoc networks and wireless sensor networks, and mobile communication systems."},
  {"id": "CSC4222", "code": "CSC 4222", "title": "Fundamentals of Cybersecurity", "credits": 4, "level": 4222, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "", "offered": [3, 1, 4, 3, 1, 4, 3, 1, 3], "description": "This course provides an initial overview on the topic of Information Security. It covers the basics of encryption and decryption, program security including viruses and other malicious code, application security, security in operating systems, security in networks and distributed systems, different methods of administering security, and legal and ethical issues in computer security."},
  {"id": "CSC4223", "code": "CSC 4223", "title": "Privacy", "credits": 4, "level": 4223, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", ["MATH3020", "MATH3030"]], "prereqText": "CSC 2720 and either MATH 3020 or MATH 3030 with a C or higher.", "note": "", "offered": [0, 0, 0, 1, 0, 0, 1, 0, 0], "description": "This course will study privacy in a few settings where rigorous definitions and enforcement mechanisms are being developed. This includes statistical disclosure limitation, semantics and logical specification of privacy policies that constrain information flow and use, principled audit and accountability mechanisms for enforcing privacy policies, anonymous communication protocols, and other settings such as in social networks, location privacy and Web privacy."},
  {"id": "CSC4226", "code": "CSC 4226", "title": "Secure Software Engineering", "credits": 4, "level": 4226, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 2, 0, 0, 2], "description": "This course is a study of the foundation of software security. Students will learn the characteristics of secure software, the role of security in the development lifecycle, designing secure software, best security programming practices, security for web applications, static analysis techniques, and software security testing."},
  {"id": "CSC4227", "code": "CSC 4227", "title": "Network Security", "credits": 4, "level": 4227, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC4220"], "prereqText": "CSC 4220 with a C or higher or equivalent (2024–25 catalog).", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "This course provides students with a detailed understanding of the fundamentals of network security and related topics. Topics to be covered include: Security standards-SSL/TLS and SET, PGP and S/MIME for electronic mail security, Firewalls, IDS, Secret Key and Public/Private Key Cryptography Cryptographic Hashes and Message Digests, Authentication Systems (Kerberos), Digital signatures and digital certificates."},
  {"id": "CSC4228", "code": "CSC 4228", "title": "Security in Internet of Things", "credits": 4, "level": 4228, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 (PAWS, Fall 2026).", "note": "The 2024–25 catalog listed CSC 4220 as the prerequisite; PAWS now requires CSC 2720 and CSC 3320.", "offered": [0, 0, 2, 0, 0, 2, 0, 0, 2], "description": "This course provides a comprehensive understanding of security concerns and solutions in the Internet of Things (IoT) realm. Students will delve into fundamental security services, techniques, and emerging IoT applications, such as AR/VR, connected and automated vehicles, and smart homes."},
  {"id": "CSC4260", "code": "CSC 4260", "title": "Digital Image Processing", "credits": 4, "level": 4260, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"]], "prereqText": "CSC 2720 or DSCI 2720 with a C or higher.", "note": "", "offered": [1, 0, 1, 1, 0, 1, 1, 0, 1], "description": "Fundamentals of image processing, including image digitization, description, enhancement, segmentation, image transforms, filtering, restoration, coding, and retrieval. Concepts are illustrated by laboratory sessions in which these techniques are applied to practical situations, including examples from industrial and biomedical image processing."},
  {"id": "CSC4311", "code": "CSC 4311", "title": "Cloud Computing", "credits": 4, "level": 4311, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"]], "prereqText": "CSC 2720 or DSCI 2720 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 1, 0], "description": "This course covers topics related to cloud computing including cloud computing infrastructure such as Infrastructure as a Service (IaaS), Platform as a Service (PaaS), and Software as a Service (SaaS). Popular cloud services such as AWS, Microsoft Azure and Google Cloud will be introduced. Container technologies such as Docker, Kubernetes etc. will be introduced."},
  {"id": "CSC4360", "code": "CSC 4360", "title": "Mobile Application Development", "credits": 4, "level": 4360, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "", "offered": [2, 2, 2, 2, 0, 2, 2, 0, 2], "description": "Crosslisted with CSC 6360. Crosslisted with CSc 6360. This course will cover the technologies, tools, frameworks and languages that are most commonly used in developing mobile applications for multiple mobile platforms. Topics include mobile application design, user interfaces, mobile application demographic and platform delivery, mobile networking, hosting infrastructure, and mobile security."},
  {"id": "CSC4370", "code": "CSC 4370", "title": "Web Programming", "credits": 4, "level": 4370, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [3, 2, 2, 2, 1, 2, 2, 1, 2], "description": "The course introduces the student to programming techniques required to develop Web applications. Topics include: HTML forms, JavaScript, Servlets and Java Server Pages, PHP and MySQL, Web access to Oracle databases, and XML."},
  {"id": "CSC4510", "code": "CSC 4510", "title": "Automata", "credits": 4, "level": 4510, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "", "offered": [0, 0, 2, 0, 0, 2, 0, 0, 2], "description": "Theory of computing devices and the languages they recognize. Deterministic and non-deterministic finite automata, context-free grammars, pushdown automata, Turing machines and undecidability."},
  {"id": "CSC4610", "code": "CSC 4610", "title": "Numerical Analysis I", "credits": 3, "level": 4610, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["MATH2215"], "prereqText": "MATH 2215 with a C or higher and the ability to program in a high-level language.", "note": "Same as MATH 4610. Needs MATH 2215 first.", "offered": [0, 0, 0, 0, 0, 1, 0, 0, 1], "description": "Same as MATH 4610. (Same as Math 4610.) Nature of error; iteration; techniques for nonlinear systems; zeros of functions; interpolation; numerical differentiation; Newton-Cotes formulae for definite integrals; computer implementation of algorithms."},
  {"id": "CSC4620", "code": "CSC 4620", "title": "Numerical Analysis II", "credits": 3, "level": 4620, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["MATH2641", "MATH2215"], "prereqText": "Either MATH 3030, or both MATH 2641 and MATH 2215, with a C or higher.", "note": "Same as MATH 4620.", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "Same as MATH 4620. (Same as MATH 4620.) Gaussian Elimination for linear systems; least squares; Taylor, predictor-corrector and Runge- Kutta methods for solving ordinary differential equations; boundary value problems; partial differential equations."},
  {"id": "CSC4710", "code": "CSC 4710", "title": "Database Systems", "credits": 4, "level": 4710, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "", "offered": [3, 0, 3, 3, 0, 3, 3, 1, 3], "description": "An introduction to the fundamental concepts and principles that underlie the relational model of data. Topics include formal query languages; SQL; query optimization; relational database design theory; physical database design, integrity, security, and concurrency control."},
  {"id": "CSC4720", "code": "CSC 4720", "title": "Human-Computer Interaction", "credits": 4, "level": 4720, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 1, 0, 0, 0, 0, 0], "description": "Techniques and methodologies for development of user interfaces in software systems; topics include interaction styles, interaction devices, user documentation, and interface assessment."},
  {"id": "CSC4730", "code": "CSC 4730", "title": "Data Visualization", "credits": 4, "level": 4730, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "Same as CMIS 4200. Data visualization or displaying data in visual forms and is closely related to data analytics. In this class, students will study the theories of data visualization, design principles, and data visualization techniques. Students will learn the various tools for creating interactive data visualizations, such as charts, maps, graphs and specialized data visualizations. (Same as CMIS 4200.)"},
  {"id": "CSC4740", "code": "CSC 4740", "title": "Data Mining", "credits": 4, "level": 4740, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "", "offered": [1, 0, 1, 1, 0, 1, 1, 0, 1], "description": "Introduction to basic data mining techniques (such as association rules mining, cluster analysis, and classification methods) and their applications (such as Web data mining, biomedical data mining and security)."},
  {"id": "CSC4760", "code": "CSC 4760", "title": "Big Data Programming", "credits": 4, "level": 4760, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "", "offered": [3, 1, 2, 1, 1, 2, 0, 1, 1], "description": "Crosslisted with CSC 6760. Crosslisted with CSc 6760. This course will cover the technologies, tools, frameworks and languages that are most commonly used in Big Data Programming. Focus will be on algorithms for analyzing and mining massive datasets, graphs and social network data. Topics include the storage, management, processing and analysis of massive datasets, as well as Big Data governance, security, and privacy issues."},
  {"id": "CSC4810", "code": "CSC 4810", "title": "Artificial Intelligence", "credits": 4, "level": 4810, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"]], "prereqText": "CSC 2720 or DSCI 2720 with a C or higher.", "note": "", "offered": [2, 0, 2, 2, 0, 2, 2, 0, 2], "description": "An overview of techniques and methodologies in the field of artificial intelligence. Topics may include search strategies, problem solving, natural language processing, logic and deduction, memory models, learning, expert systems, knowledge representation, and robotics."},
  {"id": "CSC4814", "code": "CSC 4814", "title": "Efficient Artificial Intelligence", "credits": 4, "level": 4814, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 1], "description": "This course explores principles and practices for designing and deploying artificial intelligence systems that are efficient in computation, energy, and memory. Students will learn how to optimize AI models and algorithms for real-world constraints, with a focus on mobile, embedded, and edge platforms. Topics include model compression and quantization, hardware-aware neural architecture search, efficient training and inference methods, and emerging system support for efficient AI. Through lectures, readings, and hands-on projects, students will gain both theoretical foundations and practical skills to build AI solutions that balance accuracy, scalability, and efficiency."},
  {"id": "CSC4820", "code": "CSC 4820", "title": "Interactive Computer Graphics", "credits": 4, "level": 4820, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 2, 0, 0, 2, 0, 0, 2], "description": "Same as CMIS 3150. This course will introduce students to 3D computer graphics and game programming. Students will learn how to develop 3D games and interactive computer graphics applications (such as virtual reality) using game engines. The topics include rendering, lighting, camera, sound, character control, animation, and physics. (Same as CMIS 3150.)"},
  {"id": "CSC4821", "code": "CSC 4821", "title": "Fundamentals of Game Design", "credits": 4, "level": 4821, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 2, 0, 0, 2, 0, 0, 2], "description": "Covers major aspects of game design such as challenges, gameplay, actions, core mechanics, worlds, characters, game balancing, user interfaces, and game genres."},
  {"id": "CSC4840", "code": "CSC 4840", "title": "Advanced Computer Graphics Programming", "credits": 4, "level": 4840, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "Same as CMIS 4120. Students will learn advanced 3D graphics and game programming. The topics will include rendering, lighting, camera, animation, user interaction, physics simulation, game AI, and GPU. (Same as CMIS 4120.)"},
  {"id": "CSC4841", "code": "CSC 4841", "title": "Computer Animation", "credits": 4, "level": 4841, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 0, 1, 0, 0], "description": "The basics of three-dimensional computer animation including 3D modeling, lighting, texture mapping, key framing, character animation, rigid and soft body dynamics, particles, cloth, hair, fluid, etc."},
  {"id": "CSC4850", "code": "CSC 4850", "title": "Machine Learning", "credits": 4, "level": 4850, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "MATH2641"], "prereqText": "CSC 2720 and MATH 2641 with a C or better.", "note": "The 2024–25 catalog listed CSC 4520; the 2026–27 catalog and PAWS require CSC 2720 and MATH 2641.", "offered": [3, 1, 3, 4, 1, 3, 2, 1, 3], "description": "This course is intended to provide a general introduction to machine learning. This course will cover the fundamental concepts and principles of supervised learning, unsupervised learning, semi-supervised learning and reinforcement learning. Students will understand the basic knowledge of machine learning, be familiar with classic machine learning algorithms, and gain experience of designing and implementing methods in real scenario."},
  {"id": "CSC4851", "code": "CSC 4851", "title": "Introduction to Deep Learning", "credits": 4, "level": 4851, "section": "elective", "tag": "elective", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"], "MATH2641"], "prereqText": "CSC 2720 (or DSCI 2720) and MATH 2641 with a C or higher.", "note": "", "offered": [1, 0, 0, 1, 0, 1, 1, 0, 1], "description": "This course introduces the basic concepts and algorithms of deep neural networks and its applications to computer vision and natural language processing. Depending on the course progress, selected topics such as unsupervised learning and model compression will be covered. The class emphasizes the understanding of the state-of-the-art DL architectures as well as practical implementations of deep neural networks with Python."},
  {"id": "CSC4900", "code": "CSC 4900", "title": "Technical Interview Preparation II", "credits": 3, "level": 4900, "section": "elective", "tag": "limited", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720"], "prereqText": "CSC 2720 with a C or higher.", "note": "At most 4 credits from CSC 4870, 4880, 4900, 4980 and 4982 count toward the major.", "offered": [0, 0, 0, 1, 0, 1, 1, 0, 1], "description": "The course prepares students for careers in Computer Science through a collaborative program between the CSC department and strategic partners. Students will acquire skills, competencies, and work experience that will prepare them for successful careers in the field of computer science. This course covers special technical topics at the advanced level. In addition, topics such as interviewing and job preparation, effective collaboration, presentation skills, and professionalism will also be covered to prepare students for successful careers. 3"},
  {"id": "CSC4980", "code": "CSC 4980", "title": "Topics in Computer Science", "credits": 4, "level": 4980, "section": "elective", "tag": "limited", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "Consent of instructor.", "note": "Topic varies by term. At most 4 credits from CSC 4870, 4880, 4900, 4980 and 4982 count toward the major.", "offered": [0, 0, 1, 1, 0, 1, 2, 0, 2], "description": "Selected topics in Computer Science will be covered. Topics include the latest advances in computing."},
  {"id": "CSC4982", "code": "CSC 4982", "title": "Undergraduate Research in Computer Science", "credits": 4, "level": 4982, "section": "elective", "tag": "limited", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "At least 12 upper-division hours in computer science; authorization required.", "note": "Needs a faculty sponsor. At most 4 credits from CSC 4870, 4880, 4900, 4980 and 4982 count toward the major.", "offered": [2, 3, 2, 6, 3, 4, 9, 3, 3], "description": "Independent investigation of topics of common interest to student and instructor. This course may include a Signature Experience component. This course may include a Signature Experience component."},
  {"id": "CSC4110", "code": "CSC 4110", "title": "Introduction to Embedded Systems Laboratory", "credits": 4, "level": 4110, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "Same as PHYS 4110.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Same as PHYS 4110. (Same as Phys 4110.) Four lecture hours per week. Topics taken from: review of basic logic functions; automatic systems; microprocessor- based systems and applications; embedded system software survey; microprocessor-based applications; digital communications; and embedded systems programming. Four lecture hours per week."},
  {"id": "CSC4224", "code": "CSC 4224", "title": "Ethical Hacking", "credits": 4, "level": 4224, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Introduction to the methods and techniques used by computer hackers for malicious activity and by penetration testers for defensive measures. Understanding of the techniques used by intruders will lead to the design of countermeasures for secure computer systems. Students will implement hands-on experiments to learn identification of vulnerabilities in servers, websites, wireless networks, and cryptologic systems."},
  {"id": "CSC4250", "code": "CSC 4250", "title": "Malware Analysis & Defense", "credits": 4, "level": 4250, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3210"], "prereqText": "CSC 3210 and CSC 2720.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course will introduce students to the fundamentals of malware analysis and defense techniques. Using hands-on-experience students will attain an understanding of identifying the functionalities and behaviors of malicious software. Students will use a disassembler to decompose, execute, and trace each line of a program. They will also learn how to patch the executable file and modify its behavior for a more secure outcome. Students will also have the chance to examine the effects of different types of malicious software that run either natively on a Windows or a Linux platforms. Students will learn how to defend a system by tracing back the infection and identifying the vulnerability used to exploit and implant the malicious software within the system."},
  {"id": "CSC4251", "code": "CSC 4251", "title": "Computer Forensics", "credits": 4, "level": 4251, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course teaches how to obtain and analyze digital information for possible use as evidence in civil, criminal or administrative cases. The course covers the recovery and analysis of digital evidence, addressing legal and technical issues. Topics include applications of hardware and software to computer forensics, computer forensics law, volume and file system analysis, computer forensics investigations, and computer forensics in the laboratory."},
  {"id": "CSC4310", "code": "CSC 4310", "title": "Parallel & Distributed Computing", "credits": 4, "level": 4310, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3210", "CSC3320"], "prereqText": "CSC 3210 and CSC 3320 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Introduction to various parallel and distributed computing paradigms, algorithms, architectures, programming environments, and tools. Hands-on programming on both shared-memory and message-passing parallel architectures."},
  {"id": "CSC4340", "code": "CSC 4340", "title": "Compilers", "credits": 4, "level": 4340, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3210"], "prereqText": "CSC 2720 and CSC 3210 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Survey of topics related to compiler design, including parsing, table processing, code generation, and optimization."},
  {"id": "CSC4630", "code": "CSC 4630", "title": "Matlab", "credits": 4, "level": 4630, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["MATH3030"], "prereqText": "MATH 3030 with a C or higher.", "note": "Needs MATH 3030, which is not part of your plan.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course is designed to give science majors experience with the Matlab programming language. Matlab is used for scientific applications involving images, sound, and other signals. No previous programming experience is needed"},
  {"id": "CSC4650", "code": "CSC 4650", "title": "Introduction to Bioinformatics", "credits": 4, "level": 4650, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "BIOL1103", "CHEM1211"], "prereqText": "CSC 2720, BIOL 1103K (or 1103 + 1103L) and CHEM 1211K (or 1211 + 1211L) with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "The explosion in biological knowledge due to various genome projects and other high-throughput techniques has created entirely new fields and industries, and a need for trained computational biologists who are familiar with Biology, Statistics, and Computer Science. This course will introduce principles underlying current techniques in the analysis of different kinds of biological data. Topics include: sequence alignment, database searching, microarrays, structure analysis, and phylogenetic tree algorithms."},
  {"id": "CSC4750", "code": "CSC 4750", "title": "Semantic Web", "credits": 4, "level": 4750, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC2720", "DSCI2720"]], "prereqText": "CSC 2720 or DSCI 2720 with a C or higher.", "note": "", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "In-depth overview of the Semantic Web and how it can be applied. Major topics include core technical components and language constructs for the Semantic Web, linked data concepts/projects and RDF triple stores, and real world semantic Web applications."},
  {"id": "CSC4812", "code": "CSC 4812", "title": "Simulation & AI", "credits": 4, "level": 4812, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC2720", "CSC3320"], "prereqText": "CSC 2720 and CSC 3320 with a C or higher.", "note": "New in the 2026–27 catalog.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course introduces fundamental concepts and techniques in simulation and AI for studying dynamic systems. It covers both knowledge-based approaches for developing simulation models and data-based approaches for developing AI and machine learning models. Application of these approaches to real world problems will be discussed and demonstrated."},
  {"id": "CSC4822", "code": "CSC 4822", "title": "Mobile Game Development", "credits": 3, "level": 4822, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": ["CSC3320"], "prereqText": "CSC 3320 with a C or higher.", "note": "New in the 2026–27 catalog. Same as CMIS 4318.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Same as CMIS 4318. This course focuses on developing games for mobile platforms. Topics include mobile platforms, mobile game design principles, game engine, graphics, game physics, audio, mobile game input, playtesting, and publishing."},
  {"id": "CSC4830", "code": "CSC 4830", "title": "Extended Reality Engineering", "credits": 4, "level": 4830, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC3320", "CSC3350"]], "prereqText": "CSC 3320 or CSC 3350 with a C or higher.", "note": "New in the 2026–27 catalog.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course offers an overview of extended reality (XR) engineering characteristics and introduces the development approaches, focusing on the life cycle and key activities at each stage of XR development."},
  {"id": "CSC4854", "code": "CSC 4854", "title": "Introduction to Explainable AI", "credits": 4, "level": 4854, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [["CSC4850", "CSC4851"]], "prereqText": "CSC 4850 or CSC 4851 with a C or higher.", "note": "New in the 2026–27 catalog.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "This course is intended to teach students eXplainable AI (XAI) terminologies and the state-of-the art XAI methods for diverse applications and data modalities so that they gain hands-on experience to build trustworthy AI models for many real-world domains."},
  {"id": "CSC4981", "code": "CSC 4981", "title": "Topics in Computer Science II", "credits": 4, "level": 4981, "section": "elective", "tag": "rare", "kind": "Lecture", "parts": [], "aliases": [], "prereq": [], "prereqText": "Consent of instructor.", "note": "New in the 2026–27 catalog; ask your advisor how Degree Works counts it.", "offered": [0, 0, 0, 0, 0, 0, 0, 0, 0], "description": "Selected topics in Computer Science will be covered. Topics include the latest advances in computing."},
];

/* ─── Suggested paths (planner toolbar) ───────────────────────────────────── */
const SUGGESTED_PATHS = [
  {"id": "three", "name": "3 semesters", "graduation": "December 2027", "emoji": "⚡", "note": "Fastest: 18 credits every term, including a 7-week summer (June 7 – August 2, 2027). No room to retake a course.", "terms": {"spring2027": ["CSC3210", "CSC3320", "MATH3020", "CSC3350", "CSC4710"], "summer2027": ["CSC4520", "CSC4320", "CSC4350", "CSC4222", "PERS2001"], "fall2027": ["PHYS2212", "CSC4370", "CSC4810", "MATH2641", "ECON2105"]}},
  {"id": "four", "name": "4 semesters", "graduation": "May 2028", "emoji": "🌿", "note": "Lighter loads and a lighter summer. A 4-credit Field of Study course and a 3-credit program elective meet those totals without extra waivers.", "terms": {"spring2027": ["CSC3210", "CSC3320", "MATH3020", "CSC3350"], "summer2027": ["CSC4520", "CSC4350", "MATH2641"], "fall2027": ["PHYS2212", "CSC4320", "CSC4710", "MATH2215"], "spring2028": ["CSC4222", "CSC4370", "CSC4810", "ECON2106"]}},
];
const DEFAULT_PATH_ID = "three";
// Earlier suggested paths — an untouched copy of one of these is upgraded automatically.
const LEGACY_SUGGESTED_PLANS = [{"spring2027": ["CSC3350", "MATH3020", "CSC3320", "ECON2105"], "summer2027": ["MATH2641", "CSC3210"], "fall2027": ["CSC4351", "CSC4520", "PHYS2212", "CSC4710"], "spring2028": ["CSC4352", "CSC4320", "CSC4222", "CSC4850"], "summer2028": ["CSC4370", "ECON2106"]}, {"exam": ["ECON2105"], "spring2027": ["CSC3210", "CSC3320", "MATH3020", "CSC3350", "CSC4710"], "summer2027": ["CSC4520", "CSC4320", "CSC4350", "CSC4222"], "fall2027": ["PHYS2212", "CSC4370", "CSC4810", "MATH2641", "ECON2106"]}];

const DEGREE_RULES = ["Earn a C or higher in every CSC and MATH course. Lower grades don’t count toward the degree, and GSU enforces prerequisites at registration.", "A prerequisite cannot be taken in the same term as the course that needs it.", "Up to 18 credit hours per term, summer included, without special permission (catalog 1330.30). More than 18 needs a petition and an earlier GSU term of 15+ hours with a 3.00 term GPA.", "Summer has no 15-week session. Most courses run 7 weeks (Summer 2027: June 7 – August 2), plus a 3-week May session (May 10 – June 4).", "Keep a 2.0 GPA. At most 12 hours of D grades can count toward the degree.", "GPA: A+ 4.30 down to D 1.00; F and WF are 0. W, WM, I, IP, S, U, V, K and NR never count. GPAs round to the hundredth (catalog 1350.20).", "Repeat to Replace: retake the course at GSU for a higher grade, then apply to leave the first grade out of the GPA — at most 4 courses, and it can’t be undone (catalog 1350.25)."];
const PLANNER_NOTES = ["Optional idea, not used in either path: a GSU-approved CLEP exam (for example Principles of Macroeconomics) could stand in for a 3-credit course later. Talk to your advisor before registering for one."];
